In [17]:
import pandas as pd
import requests

In [18]:
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=f17291f5c4894980315fb99a78079764&language=en-US&page=1')

In [19]:
pd.DataFrame(response.json()['results']).head(2)[['id','title','overview','release_date','popularity','vote_average','vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,95.112,8.7,17034
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,76.904,8.7,22789

In [20]:
df=pd.DataFrame()

In [21]:
df

Empty DataFrame
Columns: []
Index: []

In [22]:
for i in range(1,429):
    response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=f17291f5c4894980315fb99a78079764&language=en-US&page={}'.format(i))
    temp_df=pd.DataFrame(response.json()['results']).head(2)[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df=df.append(temp_df,ignore_index=True)

In [23]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,95.112,8.7,17034
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,76.904,8.7,22789
2,761053,Gabriel's Inferno: Part III,The final part of the film adaption of the ero...,2020-11-19,37.880,8.5,1000
3,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,33.147,8.5,10728
4,1891,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",1980-05-20,23.302,8.4,14798
5,255709,Hope,After 8-year-old So-won narrowly survives a br...,2013-10-02,18.514,8.4,464
6,914,The Great Dictator,Dictator Adenoid Hynkel tries to expand his em...,1940-10-15,16.959,8.3,2765
7,128,Princess Mononoke,"Ashitaka, a prince of the disappearing Emishi ...",1997-07-12,32.163,8.3,6668
8,975,Paths of Glory,A commanding officer defends three scapegoats ...,1957-10-25,12.163,8.3,2328
9,762975,Purple Hearts,An aspiring musician agrees to a marriage of c...,2022-07-29,57.596,8.3,1742
10,1585,It's a Wonderful Life,A holiday favourite for generations... George...,1946-12-20,40.587,8.3,3511
11,572154,Rascal Does Not Dream of a Dreaming Girl,"In Fujisawa, Sakuta Azusagawa is in his second...",2019-06-15,32.698,8.3,413
12,5156,Bicycle Thieves,A working man's livelihood is threatened when ...,1948-11-24,13.025,8.2,1962
13,284,The Apartment,Bud Baxter is a minor clerk in a huge New York...,1960-06-21,16.592,8.2,1831
14,26451,Investigation of a Citizen Above Suspicion,"Rome, Italy. After committing a heinous crime,...",1970-10-16,9.557,8.2,631
15,2457,Children of Paradise,"Filmed during the German occupation, this Fren...",1945-03-15,7.370,8.2,316
16,20532,Sansho the Bailiff,In medieval Japan a compassionate governor is ...,1954-03-31,11.860,8.2,285
17,406997,Wonder,The story of August Pullman – a boy with facia...,2017-11-13,23.717,8.2,7096
18,548,Rashomon,Brimming with action while incisively examinin...,1950-08-26,15.658,8.1,1759
19,996,Double Indemnity,A rich woman and a calculating insurance agent...,1944-06-14,10.331,8.1,1450
20,12445,Harry Potter and the Deathly Hallows: Part 2,"Harry, Ron and Hermione continue their quest t...",2011-07-07,151.572,8.1,17979
21,149871,The Tale of The Princess Kaguya,Found inside a shining stalk of bamboo by an o...,2013-11-23,15.948,8.1,1425
22,334543,Lion,A five-year-old Indian boy gets lost on the st...,2016-11-24,14.023,8.1,5888
23,46738,Incendies,A mother's last wishes send twins Jeanne and S...,2010-09-04,16.424,8.1,2058
24,449176,"Love, Simon",Everyone deserves a great love story. But for ...,2018-02-16,23.147,8.1,5528
25,10681,WALL·E,WALL·E is the last robot left on an Earth that...,2008-06-22,56.844,8.1,16398
26,37793,Ghosts,"In the town of Normal Valley, an eccentric mag...",1997-09-04,7.337,8.0,203
27,574074,Kitbull,An unlikely connection sparks between two crea...,2019-01-18,7.825,8.0,283
28,14,American Beauty,"Lester Burnham, a depressed suburban father in...",1999-09-15,29.066,8.0,10651
29,550205,Wish Dragon,Determined teen Din is longing to reconnect wi...,2021-01-15,56.058,8.0,1009
...,...,...,...,...,...,...,...
826,10351,Wishmaster,The Djinn having been released from his ancien...,1997-09-19,12.852,6.0,465
827,64635,Total Recall,"Welcome to Rekall, the company that can turn y...",2012-08-02,40.596,6.0,4842
828,491473,Gloria Bell,Gloria is a free-spirited divorcée who spends ...,2019-03-07,8.229,6.0,265
829,215830,Open Grave,A man awakes-- without memory -- in a pit full...,2013-08-13,10.252,6.0,605
830,4858,The Invasion,"Washington, D.C. psychologist Carol Bennell an...",2007-08-17,17.056,6.0,1241
831,426238,Beach Rats,An aimless teenager on the outer edges of Broo...,2017-08-25,12.429,6.0,444
832,130267,Seal Team Six: The Raid on Osama Bin Laden,When the rumored whereabouts of Osama bin Lade...,2012-11-04,5.426,6.0,242
833,586592,Come to Daddy,After receiving a cryptic letter from his estr...,2019-04-25,9.163,6.0,414
834,172533,Drinking Buddies,"Weekend trips, office parties, late night conv...",2013-08-23,9.350,5.9,708
835,86331,Desire,In a social context deteriorated by a countryw...,2011-10-06,88.947,5.9,598
836,48946,Chatroom,"When strangers Jim, Eva, Emily and Mo meet Wil...",2010-08-11,8.577,5.9,256
837,14372,Leviathan,Underwater deep-sea miners encounter a Soviet ...,1989-03-17,13.960,5.9,395
838,24056,The Tournament,Every ten or seven years in an unsuspecting to...,2009-05-01,12.767,5.9,520
839,471507,Destroyer,"When Erin Bell was a young cop, she was given ...",2018-12-25,11.965,5.9,603
840,514593,You Should Have Left,"In an effort to repair their relationship, a c...",2020-06-18,17.767,5.9,546
841,335777,The Nut Job 2: Nutty by Nature,When the evil mayor of Oakton decides to bulld...,2017-08-11,19.842,5.9,339
842,37958,Immortals,Theseus is a mortal man chosen by Zeus to lead...,2011-11-10,21.770,5.9,2194
843,34480,The Descent: Part 2,"Distraught, confused, and half-wild with fear,...",2009-10-14,22.126,5.9,898
844,267193,Grimsby,"Wrongfully accused and on the run, a top MI6 a...",2016-02-24,19.305,5.9,1995
845,58224,Mr. Popper's Penguins,"Jim Carrey stars as Tom Popper, a successful b...",2011-06-17,23.730,5.9,2554
846,9417,Wrongfully Accused,"Ryan Harrison, a violin god, superstar and sex...",1998-07-23,10.992,5.9,326
847,10280,Thinner,"An obese lawyer finds himself growing ""Thinner...",1996-10-25,11.042,5.9,484
848,375588,Robin Hood,A war-hardened Crusader and his Moorish comman...,2018-11-21,23.338,5.9,2603
849,340945,USS Indianapolis: Men of Courage,The harrowing true story of the crew of the US...,2016-09-22,17.351,5.9,532
850,539537,Fantasy Island,A group of contest winners arrive at an island...,2020-02-12,17.862,5.9,2052
851,157843,Queen of the Desert,"A chronicle of Gertrude Bell's life, a travele...",2015-09-03,7.598,5.9,232
852,10093,The Return,Joanna Mills has a successful career but feels...,2006-11-10,9.117,5.9,522
853,10066,House of Wax,A group of unwitting teens are stranded near a...,2005-04-30,26.453,5.9,2542
854,34311,Sleepaway Camp II: Unhappy Campers,Angela Baker escapes from a mental hospital an...,1988-10-31,11.842,5.9,210
855,17134,12 Rounds,When New Orleans Police Detective Danny Fisher...,2009-03-19,23.106,5.9,648

In [24]:
df.shape

(856, 7)

In [31]:
df.to_csv('moviesfinal.csv')

UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 160: ordinal not in range(128)